### ISSUE TITLE
[Modern] User list broken

### ISSUE THREAD

**Issue by DoM1niC** [traccar/traccar-web#898]
Current master the user list give a white Page

```
react-dom.production.min.js:216 TypeError: t is not a function
    at ct (formatter.js:3)
    at UsersPage.js:54
    at Array.map (<anonymous>)
    at ur (UsersPage.js:45)
    at na (react-dom.production.min.js:157)
    at Ba (react-dom.production.min.js:180)
    at Vs (react-dom.production.min.js:269)
    at Eu (react-dom.production.min.js:250)
    at _u (react-dom.production.min.js:250)
    at xu (react-dom.production.min.js:250)
is @ react-dom.production.min.js:216
formatter.js:3 Uncaught (in promise) TypeError: t is not a function
    at ct (formatter.js:3)
    at UsersPage.js:54
    at Array.map (<anonymous>)
    at ur (UsersPage.js:45)
    at na (react-dom.production.min.js:157)
    at Ba (react-dom.production.min.js:180)
    at Vs (react-dom.production.min.js:269)
    at Eu (react-dom.production.min.js:250)
    at _u (react-dom.production.min.js:250)
    at xu (react-dom.production.min.js:250)
```

**Comment by tananaev** [comment]
1. Are you using the official release?
2. Have you cleared your browser cache?
3. Can I have access to your server to take a look? You can send over email if you don't want to share.

**Comment by DoM1niC** [comment]
> 1. Are you using the official release?
> 2. Have you cleared your browser cache?
> 3. Can I have access to your server to take a look? You can send over email if you don't want to share.

Hey @tananaev I compiled the master of the modern web UI with yarn install & yarn build with the latest LTS 16.9.x

**Comment by akosaz** [comment]
In _/admin/UsersPage.js_
`<TableCell>{formatBoolean(item, 'administrator', t)}</TableCell>` 
breaks the translation

This should fix it
`<TableCell>{formatBoolean(item['administrator'], t)}`
